package org.ies.tierno.readers;

import org.ies.tierno.files.AudioFile;
import org.ies.tierno.program.Program;

public class AudioProgramReader implements Reader<Program<AudioFile>> {

    @Override
    public Program<AudioFile> read() {
        AudioFile[] files = {
                new AudioFile(6200, "Musica/Liszt - Hungarian Rhapsody No.2.mp3", 600),
                new AudioFile(5100, "Musica/Liszt - Liebestraum No.3.mp3", 320),
                new AudioFile(5700, "Musica/Liszt - La Campanella.mp3", 260),
                new AudioFile(6500, "Musica/Liszt - Piano Concerto No.1 - I.mp3", 540),
                new AudioFile(6400, "Musica/Liszt - Piano Concerto No.1 - II.mp3", 430),
                new AudioFile(6600, "Musica/Liszt - Piano Concerto No.1 - III.mp3", 420),
                new AudioFile(6000, "Musica/Liszt - Totentanz.mp3", 420),
                new AudioFile(5900, "Musica/Liszt - Mephisto Waltz No.1.mp3", 500),
                new AudioFile(5000, "Musica/Chopin - Nocturne Op.9 No.2.mp3", 290),
                new AudioFile(5400, "Musica/Chopin - Nocturne Op.27 No.2.mp3", 330),
                new AudioFile(5300, "Musica/Chopin - Ballade No.1 Op.23.mp3", 420),
                new AudioFile(6000, "Musica/Chopin - Ballade No.4 Op.52.mp3", 500),
                new AudioFile(5200, "Musica/Chopin - Polonaise Op.53 (Heroic).mp3", 300),
                new AudioFile(4800, "Musica/Chopin - Etude Op.10 No.12 (Revolutionary).mp3", 220),
                new AudioFile(5200, "Musica/Chopin - Prelude Op.28 No.4.mp3", 110),
                new AudioFile(5100, "Musica/Chopin - Prelude Op.28 No.15 (Raindrop).mp3", 290),
                new AudioFile(5000, "Musica/Chopin - Waltz Op.64 No.2.mp3", 210),
                new AudioFile(5600, "Musica/Chopin - Scherzo No.2 Op.31.mp3", 430),
                new AudioFile(6800, "Musica/Stravinsky - The Firebird (Suite) - Finale.mp3", 520),
                new AudioFile(6200, "Musica/Stravinsky - The Rite of Spring - Part I.mp3", 530),
                new AudioFile(6400, "Musica/Stravinsky - The Rite of Spring - Part II.mp3", 560),
                new AudioFile(5000, "Musica/Stravinsky - Petrushka (Suite) - Russian Dance.mp3", 230),
                new AudioFile(5200, "Musica/Stravinsky - Petrushka (Suite) - Petrushka's Room.mp3", 280),
                new AudioFile(5100, "Musica/Stravinsky - Pulcinella Suite - I.mp3", 360),
                new AudioFile(5200, "Musica/Stravinsky - Pulcinella Suite - II.mp3", 320),
                new AudioFile(6200, "Musica/Rachmaninov - Piano Concerto No.2 - I.mp3", 620),
                new AudioFile(6100, "Musica/Rachmaninov - Piano Concerto No.2 - II.mp3", 420),
                new AudioFile(6300, "Musica/Rachmaninov - Piano Concerto No.2 - III.mp3", 560),
                new AudioFile(5600, "Musica/Rachmaninov - Piano Concerto No.3 - I.mp3", 700),
                new AudioFile(5500, "Musica/Rachmaninov - Piano Concerto No.3 - II.mp3", 460),
                new AudioFile(5800, "Musica/Rachmaninov - Piano Concerto No.3 - III.mp3", 620),
                new AudioFile(5400, "Musica/Rachmaninov - Rhapsody on a Theme of Paganini - Variation 18.mp3", 220),
                new AudioFile(6500, "Musica/Rachmaninov - Symphonic Dances - I.mp3", 450),
                new AudioFile(6300, "Musica/Rachmaninov - Symphonic Dances - II.mp3", 350),
                new AudioFile(6400, "Musica/Rachmaninov - Symphonic Dances - III.mp3", 520),
                new AudioFile(5200, "Musica/Verdi - La Traviata - Brindisi.mp3", 320),
                new AudioFile(7200, "Musica/Verdi - La Traviata - Act I (Selección).mp3", 1400),
                new AudioFile(7600, "Musica/Verdi - La Traviata - Act II (Selección).mp3", 1500),
                new AudioFile(7800, "Musica/Verdi - La Traviata - Act III (Selección).mp3", 1600),
                new AudioFile(6400, "Musica/Lucia di Lammermoor - Act I (Selección).mp3", 1500),
                new AudioFile(6500, "Musica/Lucia di Lammermoor - Act II (Selección).mp3", 1600),
                new AudioFile(6600, "Musica/Lucia di Lammermoor - Act III (Selección).mp3", 1700),
                new AudioFile(5200, "Musica/Lucia di Lammermoor - Sextet (Act III).mp3", 520),
                new AudioFile(5000, "Musica/Lucia di Lammermoor - Il dolce suono (Aria).mp3", 290),
                new AudioFile(5400, "Musica/Lucia di Lammermoor - Tu che a gel sei cinta (Aria).mp3", 280),
                new AudioFile(6200, "Musica/Il pirata - Act I (Selección).mp3", 1400),
                new AudioFile(6300, "Musica/Il pirata - Act II (Selección).mp3", 1500),
                new AudioFile(6400, "Musica/Il pirata - Act III (Selección).mp3", 1600),
                new AudioFile(5000, "Musica/Il pirata - Vieni fra queste braccia (Aria).mp3", 300),
                new AudioFile(5200, "Musica/Il pirata - Oh, quante volte (Aria).mp3", 320),
                new AudioFile(7000, "Musica/Carmen - Act I (Selección).mp3", 1500),
                new AudioFile(7200, "Musica/Carmen - Act II (Selección).mp3", 1600),
                new AudioFile(7400, "Musica/Carmen - Act III (Selección).mp3", 1700),
                new AudioFile(7600, "Musica/Carmen - Act IV (Selección).mp3", 1800),
                new AudioFile(5200, "Musica/Carmen - Habanera.mp3", 190),
                new AudioFile(5300, "Musica/Carmen - Toreador Song.mp3", 210),
                new AudioFile(5400, "Musica/Carmen - Seguidilla.mp3", 180),
                new AudioFile(7200, "Musica/La Traviata - Act I (Selección).mp3", 1400),
                new AudioFile(7600, "Musica/La Traviata - Act II (Selección).mp3", 1500),
                new AudioFile(7800, "Musica/La Traviata - Act III (Selección).mp3", 1600),
                new AudioFile(5200, "Musica/La Traviata - Brindisi.mp3", 320),
                new AudioFile(6500, "Musica/La Bohème - Act I (Selección).mp3", 1400),
                new AudioFile(6700, "Musica/La Bohème - Act II (Selección).mp3", 1500),
                new AudioFile(6900, "Musica/La Bohème - Act III (Selección).mp3", 1600),
                new AudioFile(7100, "Musica/La Bohème - Act IV (Selección).mp3", 1700),
                new AudioFile(5800, "Musica/La Bohème - Che gelida manina.mp3", 160),
                new AudioFile(7600, "Musica/Don Giovanni - Act I (Selección).mp3", 1500),
                new AudioFile(7800, "Musica/Don Giovanni - Act II (Selección).mp3", 1600),
                new AudioFile(6100, "Musica/Don Giovanni - La ci darem la mano.mp3", 180),
                new AudioFile(6200, "Musica/Don Giovanni - Champagne Aria.mp3", 200)
        };
        return new Program<>(files, "Reproductor de audio VLC");
    }
}
